version: 2

models:
  - name: region
    description: "This table contains information about regions."
    columns:
      - name: R_REGIONKEY
        description: "The region key."
        tests:
          - unique
          - not_null
      - name: R_NAME
        description: "The name of the region."
        tests:
          - not_null
      - name: R_COMMENT
        description: "Comments about the region."