version: 2

models:
  - name: nation
    description: "This table contains information about nations."
    columns:
      - name: N_NATIONKEY
        description: "The nation key."
        tests:
          - unique
          - not_null
      - name: N_NAME
        description: "The name of the nation."
        tests:
          - not_null
      - name: N_REGIONKEY
        description: "The region key associated with the nation."
      - name: N_COMMENT
        description: "Comments about the nation."