version: 2

models:
  - name: supplier
    description: "This table contains information about suppliers."
    columns:
      - name: S_SUPPKEY
        description: "The supplier key."
        tests:
          - unique
          - not_null
      - name: S_NAME
        description: "The name of the supplier."
        tests:
          - not_null
      - name: S_ADDRESS
        description: "The address of the supplier."
      - name: S_NATIONKEY
        description: "The nation key associated with the supplier."
      - name: S_PHONE
        description: "The phone number of the supplier."
      - name: S_ACCTBAL
        description: "The account balance of the supplier."
      - name: S_COMMENT
        description: "Comments about the supplier."