version: 2

models:
  - name: customer_model
    description: "This model selects all columns from the TPCH_SF1.CUSTOMER table."
    columns:
      - name: C_CUSTKEY
        description: "The primary key for the customer."
        tests:
          - unique
          - not_null
      - name: C_NAME
        description: "The name of the customer."
        tests:
          - not_null
      - name: C_ADDRESS
        description: "The address of the customer."
      - name: C_NATIONKEY
        description: "The nation key associated with the customer."
      - name: C_PHONE
        description: "The phone number of the customer."
      - name: C_ACCTBAL
        description: "The account balance of the customer."
      - name: C_MKTSEGMENT
        description: "The market segment of the customer."
      - name: C_COMMENT
        description: "Comments about the customer."